/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CCredits.java
 *
 * Created on 27-jun-2010, 14:50:07
 */

package GUI;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Yulio
 */
public class CCredits extends javax.swing.JDialog {
//    private Image fondo;

    /** Creates new form CCreditos */
    public CCredits(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
//        try {
//            loadImage();
//        } catch (IOException ex) {
//            Logger.getLogger(CCredits.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        paintComponent(this.getGraphics());
        this.setLocationRelativeTo(this);
    }

//    private void loadImage() throws  IOException {
//        fondo = (Image) ImageIO.read(new File("./Images/Fondos/Creditos.jpg"));
//    }
//
//    protected void paintComponent(Graphics g) {
//        g.drawImage(fondo, 0, 0, this);
//    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca de Parchís 1.0");
        setMinimumSize(new java.awt.Dimension(669, 325));
        setUndecorated(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Backs/Creditos.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_formMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
//        this.setLocation(200,200/*Integer.parseInt(String.valueOf(dim.getWidth()/2 - this.getWidth()/2)),Integer.parseInt(String.valueOf( dim.getHeight()/2 - this.getHeight()))*/);
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CCredits dialog = new CCredits(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
