/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDPlayersSelector.java
 *
 * Created on 19-jun-2010, 16:57:39
 */
package GUI;

import Clases.CPlayer;
import Clases.CAIPlayerKnight;
import Clases.CAIPlayerSquire;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Yulio
 */
public class JDPlayersSelector extends javax.swing.JDialog {

    CPlayer[] players;

    int nPlayers;

    String[] houses = {
        "Vacio",
        "Night King",
        "Stark",
        "Baratheon",
        "Lanister",
        "Targaryen",
        "Arryn",
        "Martell",
        "Tyrell",
        "Greyjoy",
        "Tully"
    };

    /**
     * Creates new form jDSelectorJugadores
     */
    public JDPlayersSelector(CMainFrame parent, boolean modal, CPlayer[] players) {
        super(parent, modal);
        initComponents();
        this.players = players;
        this.nPlayers = 0;
//        try {
//            this.setIconImage((Image)ImageIO.read(new File("./Images/Iconos/about.png")));
//        } catch (IOException ex) {
//            Logger.getLogger(JDPlayersSelector.class.getName()).log(Level.SEVERE, null, ex);
//        }
        this.setLocationRelativeTo(this);
    }

    public void marcarJugadores() {
        if (PlayerSelector2.getSelectedIndex() != 0) {
            jComboBox2.setEnabled(true);
            jTextField2.setEnabled(true);
        } else {
            jComboBox2.setEnabled(false);
            jTextField2.setEnabled(false);
        }

        if (PlayerSelector3.getSelectedIndex() != 0) {
            jComboBox3.setEnabled(true);
            jTextField3.setEnabled(true);
        } else {
            jComboBox3.setEnabled(false);
            jTextField3.setEnabled(false);
        }

        if (PlayerSelector4.getSelectedIndex() != 0) {
            jComboBox4.setEnabled(true);
            jTextField4.setEnabled(true);
        } else {
            jComboBox4.setEnabled(false);
            jTextField4.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        PlayerSelector1 = new javax.swing.JComboBox();
        PlayerSelector2 = new javax.swing.JComboBox();
        PlayerSelector3 = new javax.swing.JComboBox();
        PlayerSelector4 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose Players");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Choose Players", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 36))); // NOI18N
        jPanel1.setName(""); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Shoose House --", "Night King", "Stark", "Baratheon", "Lanister", "Targaryen", "Arryn", "Martell", "Tyrell", "Greyjoy", "Tully" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Shoose House --", "Night King", "Stark", "Baratheon", "Lanister", "Targaryen", "Arryn", "Martell", "Tyrell", "Greyjoy", "Tully" }));
        jComboBox2.setEnabled(false);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Shoose House --", "Night King", "Stark", "Baratheon", "Lanister", "Targaryen", "Arryn", "Martell", "Tyrell", "Greyjoy", "Tully" }));
        jComboBox3.setEnabled(false);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Shoose House --", "Night King", "Stark", "Baratheon", "Lanister", "Targaryen", "Arryn", "Martell", "Tyrell", "Greyjoy", "Tully" }));
        jComboBox4.setEnabled(false);

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setText("Name ...");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jTextField2.setText("Name ...");
        jTextField2.setEnabled(false);
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jTextField3.setText("Name ...");
        jTextField3.setEnabled(false);
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });

        jTextField4.setText("Name ...");
        jTextField4.setToolTipText("");
        jTextField4.setEnabled(false);
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        PlayerSelector1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Human", "AI Squire", "AI Knight" }));

        PlayerSelector2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Choose type --", "Human", "AI Squire", "AI Knight" }));
        PlayerSelector2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerSelector2ActionPerformed(evt);
            }
        });

        PlayerSelector3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Choose type --", "Human", "AI Squire", "AI Knight" }));
        PlayerSelector3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerSelector3ActionPerformed(evt);
            }
        });

        PlayerSelector4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Choose type --", "Human", "AI Squire", "AI Knight" }));
        PlayerSelector4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerSelector4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PlayerSelector3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PlayerSelector1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PlayerSelector2, javax.swing.GroupLayout.Alignment.LEADING, 0, 117, Short.MAX_VALUE)
                    .addComponent(PlayerSelector4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4)
                    .addComponent(jTextField3)
                    .addComponent(jTextField2)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.TRAILING, 0, 164, Short.MAX_VALUE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlayerSelector1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlayerSelector2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlayerSelector3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlayerSelector4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButton1.getAccessibleContext().setAccessibleName("OK");
        jButton1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Shoose Players");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        jTextField1.setText("Name ...");
        jTextField2.setText("Name ...");
        jTextField3.setText("Name ...");
        jTextField4.setText("Name ...");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jComboBox4.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Init Variables
        //CJugador[] jugadores = new CPlayer[4];
        int cont = 1;
        String name = "";
        int house = 0;

        // Player 1
        // Validation and reception of data
        if ((name = jTextField1.getText()).isEmpty() || jComboBox1.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Incomplete information.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
//                house = new Integer((String) jComboBox1.getSelectedItem());
        house = Arrays.asList(houses).indexOf((String) jComboBox1.getSelectedItem());

        // Creation of the player
        switch (PlayerSelector1.getSelectedIndex()) {
            case 0:
                players[0] = new CPlayer(0, name, house, false);
                break;
            case 1:
                players[0] = (new CAIPlayerSquire(0, name, house));
                break;
            case 2:
                players[0] = (new CAIPlayerKnight(0, name, house));
                break;
        }

        this.nPlayers = 1;

        // Player 2
        if (PlayerSelector2.getSelectedIndex() != 0) {
            // Validation and reception of data
            if ((name = jTextField2.getText()).isEmpty() || jComboBox2.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Incomplete information.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                cont++;
//                house = new Integer((String) jComboBox2.getSelectedItem());
                house = Arrays.asList(houses).indexOf((String) jComboBox2.getSelectedItem());

                // Creation of the player
                switch (PlayerSelector2.getSelectedIndex()) {
                    case 1:
                        players[1] = new CPlayer(0, name, house, false);
                        break;
                    case 2:
                        players[1] = (new CAIPlayerSquire(0, name, house));
                        break;
                    case 3:
                        players[1] = (new CAIPlayerKnight(0, name, house));
                        break;
                }
            }

            this.nPlayers = 2;
        }
        // Player 3
        if (PlayerSelector3.getSelectedIndex() != 0) {
            // Validation and reception of data
            if ((name = jTextField3.getText()).isEmpty() || jComboBox3.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Incomplete information.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                cont++;
//                house = new Integer((String) jComboBox3.getSelectedItem());
                house = Arrays.asList(houses).indexOf((String) jComboBox3.getSelectedItem());

                // Creation of the player
                switch (PlayerSelector3.getSelectedIndex()) {
                    case 1:
                        players[2] = new CPlayer(0, name, house, false);
                        break;
                    case 2:
                        players[2] = (new CAIPlayerSquire(0, name, house));
                        break;
                    case 3:
                        players[2] = (new CAIPlayerKnight(0, name, house));
                        break;
                }
            }

            this.nPlayers = 3;
        }
        // Player 4
        if (PlayerSelector4.getSelectedIndex() != 0) {
            // Validation and reception of data
            if ((name = jTextField4.getText()).isEmpty() || jComboBox4.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Datos incompletos", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                cont++;
//                house = new Integer((String) jComboBox4.getSelectedItem());
                house = Arrays.asList(houses).indexOf((String) jComboBox4.getSelectedItem());

                // Creation of the player
                switch (PlayerSelector4.getSelectedIndex()) {
                    case 1:
                        players[3] = new CPlayer(0, name, house, false);
                        break;
                    case 2:
                        players[3] = (new CAIPlayerSquire(0, name, house));
                        break;
                    case 3:
                        players[3] = (new CAIPlayerKnight(0, name, house));
                        break;
                }
            }
            this.nPlayers = 4;
        }

        for (int i = 0; i < this.nPlayers; i++) {
            for (int j = 0; j < this.nPlayers; j++) {
                if (i != j && players[i].getHouse() == players[j].getHouse()) {
                    JOptionPane.showMessageDialog(this, "Each player must belong to a different house.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            switch (i + 1) {
                case 1:
                    if (jTextField1.getText().equals("Name ...")) {
                        JOptionPane.showMessageDialog(this, "Player No. 1 must have a name.", "Error", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    break;
                case 2:
                    if (jTextField2.getText().equals("Name ...")) {
                        JOptionPane.showMessageDialog(this, "Player No. 2 must have a name.", "Error", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    break;
                case 3:
                    if (jTextField3.getText().equals("Name ...")) {
                        JOptionPane.showMessageDialog(this, "Player No. 3 must have a name.", "Error", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    break;
                case 4:
                    if (jTextField4.getText().equals("Name ...")) {
                        JOptionPane.showMessageDialog(this, "Player No. 4 must have a name.", "Error", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    break;
            }
        }

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        jTextField1.setText(null);
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        jTextField2.setText(null);
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        jTextField3.setText(null);
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
        jTextField4.setText(null);
    }//GEN-LAST:event_jTextField4FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        if (jTextField1.getText().equals(null)) {
            jTextField1.setText("Name ...");
        }

    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        if (jTextField2.getText().equals(null)) {
            jTextField2.setText("Name ...");
        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        if (jTextField3.getText().equals(null)) {
            jTextField3.setText("Name ...");
        }
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        if (jTextField4.getText().equals(null)) {
            jTextField4.setText("Name ...");
        }
    }//GEN-LAST:event_jTextField4FocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.players = new CPlayer[4];
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void PlayerSelector2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerSelector2ActionPerformed
        marcarJugadores();
    }//GEN-LAST:event_PlayerSelector2ActionPerformed

    private void PlayerSelector3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerSelector3ActionPerformed
        marcarJugadores();
    }//GEN-LAST:event_PlayerSelector3ActionPerformed

    private void PlayerSelector4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerSelector4ActionPerformed
        marcarJugadores();
    }//GEN-LAST:event_PlayerSelector4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
//        this.setLocation((dim.height/2) - (this.getHeight()/2), (dim.width/2) - (this.getWidth()/2));
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox PlayerSelector1;
    private javax.swing.JComboBox PlayerSelector2;
    private javax.swing.JComboBox PlayerSelector3;
    private javax.swing.JComboBox PlayerSelector4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
